### ISSUE TITLE
how to get it in edge? 

### ISSUE THREAD

**Issue by cyheng** [gaoliang/env-indicator#3]
how can I get it in edge? It seems to not be found in Edge Addons.

**Comment by gaoliang** [comment]
I submitted the Environment Indicator to the Edge Add-on store yesterday, but it's still under review.  You can use it temporarily by installing the [crx file](https://github.com/gaoliang/env-indicator/releases/tag/1.0.3) and I'll let you know when it's approved

**Comment by gaoliang** [comment]
Finally, we passed Microsoft's review and are now available at https://microsoftedge.microsoft.com/addons/detail/nlgegepgfcagnbjdnjbaoiiooklkhlcj
